# === basics ===
title: SCIONLab Tutorials
description: A collection of tutorial pages for SCION
aux_links:
  "SCIONLab":
    - "https://scionlab.org/"
  "SCION Home Page":
    - "https://scion-architecture.net/"
  "Our GitHub":
    - "https://github.com/netsec-ethz/"
footer_content: "Copyright &copy; 2020, Network Security Group, ETH Zurich"
url: https://docs.scionlab.org

# === visuals ===
remote_theme: pmarsceill/just-the-docs
logo: /favicon.ico
logo_title: SCIONLab

# === markdown options ===

markdown: kramdown
kramdown:
  toc_levels: 1..3

# === defaults ===
defaults:
  - scope: {path: "content"}
    values:
      layout: default

# === Build settings ===
exclude: [Gemfile, Gemfile.lock]
