site_name: SCION Tutorials
site_description: A collection of tutorial pages for SCION

site_dir: docs
docs_dir: content

theme:
    name: null
    custom_dir: 'mkdocs-material/material'

    include_search_page: false
    search_index_only: true

    language: en
    feature:
      tabs: false
    palette:
      primary:
      accent:
    font:
      text: Roboto
      code: Roboto Mono
    favicon: assets/images/favicon.ico
    logo:
      icon: "\uE80C"

markdown_extensions:
    - admonition
    - codehilite
    - meta
    - toc:
        permalink: true


copyright: 'Copyright &copy 2018, Network Security Group, ETH Zurich'

# Options
extra:
  search:
    languages: 'en'

  social:
    - type: globe
      link: https://www.scion-architecture.net/
    - type: github-alt
      link: https://github.com/netsec-ethz/

pages:
    - Home: index.md

    - How to run SCION VM:
      - Virtual machine with VPN: virtual_machine_setup/dynamic_ip.md
      - Virtual machine with static public IP: virtual_machine_setup/static_ip.md

    - How to install SCION manually on different platforms:
      - Ubuntu 16.04 x86-64: native_setup/ubuntu_x86_build.md
      - Ubuntu MATE Raspberry PI: native_setup/rpi_ubuntu.md
      - Android devices: native_setup/android.md

    - Connecting to SCION:
      - Running SCION on a local topology: general_scion_configuration/local_top.md
      - Set up an AS and connect to the SCION network: general_scion_configuration/public_ip.md
      - Set up an AS and connect to the SCION network behind a NAT: general_scion_configuration/public_ip_nat.md
      - Set up an AS and connect to the SCION network via VPN: general_scion_configuration/vpn_setup.md
      - Set up SCION endhost and connect to local AS: general_scion_configuration/setup_endhost.md


    - How to use:
      - Read a temperature sensor over the SCION network: sample_projects/fetch_sensor_readings.md
      - Access a video camera over the SCION network: sample_projects/access_camera.md
      - Bandwidth tester application: sample_projects/bwtester.md
      - Running AS Visualizations: as_visualization/running_asviz.md
      - Browser AS Visualization: as_visualization/browser_asviz.md
      - Command-line AS Visualization: as_visualization/command_asviz.md

    - SCION tips and tricks:
      - Verifying the installation: general_scion_configuration/verifying_scion_installation.md
      - Running SCION on system boot: scion_tricks/setup_startup.md
      - Updating gen directory: scion_tricks/changing_gen_dir.md
      - Updating SCION: scion_tricks/updating_scion.md
      - Adding Wireshark dissector: scion_tricks/wireshark.md

    - SCIONLab:
      - SCION box first steps: scionlab/scionlab.md

